name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'
          maven-version: '3.x'

      - name: Restore dependencies (Maven)
        run: mvn install -DskipTests

      - name: Build the project
        run: mvn clean install --no-transfer-progress

      - name: Publish the project
        run: mvn spring-boot:build-image

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sistemadeprontuarios"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish